### ISSUE TITLE
Error importing from the game version 1.1.21. 

### ISSUE THREAD

**Issue by click0** [asheiduk/factorio-blueprint-decoder#1]
```
XXX@PC-XXX MSYS ~/factorio-blueprint-decoder
$ ./decode blueprint-storage.dat > my-bps1.json
Traceback (most recent call last):
  File "./decode", line 2404, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "./decode", line 2141, in parse_blueprint_library
    global_index = parse_index(stream, result)
  File "./decode", line 1827, in parse_index
    index.add(name_id, prototype_name, name)
  File "./decode", line 174, in add
    raise KeyError(f"unknown prototype '{prototype}'")
KeyError: "unknown prototype 'copy-paste-tool'"
```
```
$ python3
Python 3.8.6 (default, Oct 23 2020, 14:59:35)
[GCC 9.3.0] on msys
```
and other machine:
```
# python3
Python 3.8.6 (default, Oct  9 2020, 20:21:12)
[Clang 10.0.0 (git@github.com:llvm/llvm-project.git llvmorg-10.0.0-0-gd32170dbd on freebsd12
```

I can put the blueprint-storage.dat file somewhere, but it's big - 125MB.

**Comment by click0** [comment]
After adding a line with a new object 
```
81d80
<         "copy-paste-tool": ITEM,
```

We get the following error: 
```
$ ./decode blueprint-storage-old-month.dat > my-bps1.json
Traceback (most recent call last):
  File "./decode", line 2405, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "./decode", line 2144, in parse_blueprint_library
    stream.expect(0x00, 0x00)
  File "./decode", line 278, in expect
    raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
__main__.ParseError: expected 0x00 but got 0x2c at position 11034 (0x2b1a)
```

**Comment by asheiduk** [comment]
Nice report, thank you!

I will add this one and a bunch of others (according to [Prototype/Item]) tomorrow:

- "item-with-label"
- "item-with-inventory"
- "item-with-tags"
- "copy-paste-tool"
- "selection-tool"
- "mining-tool"

I omitted them because I found no way to put these into a blueprint. So: How this you do this? Are some mods involved?

[Prototype/Item]: https://wiki.factorio.com/Prototype/Item

**Comment by click0** [comment]
I copied BPs already made by someone.

**Comment by asheiduk** [comment]
fixed in #d48f3df

**Comment by click0** [comment]
> 
> 
> After adding a line with a new object
> 
> ```
> 81d80
> <         "copy-paste-tool": ITEM,
> ```
> 
> We get the following error:
> 
> ```
> $ ./decode blueprint-storage-old-month.dat > my-bps1.json
> Traceback (most recent call last):
>   File "./decode", line 2405, in <module>
>     library = parse_blueprint_library(PrimitiveStream(f))
>   File "./decode", line 2144, in parse_blueprint_library
>     stream.expect(0x00, 0x00)
>   File "./decode", line 278, in expect
>     raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
> __main__.ParseError: expected 0x00 but got 0x2c at position 11034 (0x2b1a)
> ```

What about this error? Open a new issue?

**Comment by asheiduk** [comment]
I've to admit that I did not fully comprehend the first issue. I thought that all this is about the `copy-paste-tool`. That part has been solved.

There are two other parts:
- The title mentions version 1.1.21.
    Right now the tool supports only version 1.0.0 AND the binary format has changed for 1.1.19 (the next stable version after 1.0.0). I'm decoding 1.1.19 in the next few days. For 1.1.21 I don't expect changes there.
- The second traceback shows an unexpected and unknown value.

Therefore:
- Please open another issue for support 1.1.21
- Provide a download link to your `blueprint-storage.dat` file because I need to known what this `0x2c at position 11034 (0x2b1a)` is all about.
