### ISSUE TITLE
Got error while decoding blueprint-storage.dat

### ISSUE THREAD

**Issue by kevinmama** [asheiduk/factorio-blueprint-decoder#6]
Factorio Version: 1.1.45
OS: macOS Big Sur 11.5.2
python: 3.7.0

factorio-blueprint-decoder git:(master) python3 decode ../blueprint-storage.dat > /tmp/bps-latest.json
Traceback (most recent call last):
  File "decode", line 2690, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "decode", line 2368, in parse_blueprint_library
    parse_library_objects(stream, global_index, book_item, library_version)
  File "decode", line 2036, in parse_library_objects
    handler_result = handler(stream, index, library_version)
  File "decode", line 2507, in parse_blueprint_book
    parse_library_objects(stream, index, result, library_version)
  File "decode", line 2036, in parse_library_objects
    handler_result = handler(stream, index, library_version)
  File "decode", line 2507, in parse_blueprint_book
    parse_library_objects(stream, index, result, library_version)
  File "decode", line 2036, in parse_library_objects
    handler_result = handler(stream, index, library_version)
  File "decode", line 2507, in parse_blueprint_book
    parse_library_objects(stream, index, result, library_version)
  File "decode", line 2036, in parse_library_objects
    handler_result = handler(stream, index, library_version)
  File "decode", line 2448, in parse_blueprint
    parse_entities(stream, index, result)
  File "decode", line 2158, in parse_entities
    handler(stream, index, entity)
  File "decode", line 1695, in eh_ammo_turret
    stream.expect(*[0x00]*9)
  File "decode", line 317, in expect
    raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
__main__.ParseError: expected 0x00 but got 0x01 at position 3695124 (0x386214)

[blueprint-storage.dat.zip](https://github.com/asheiduk/factorio-blueprint-decoder/files/7462655/blueprint-storage.dat.zip)

**Comment by asheiduk** [comment]
I have found these issues while examining your file:
- Gun turrets and artillery turrets have some preloaded ammo inside. That's interesting because I cannot create a blueprint like this in the vanilla game. Did you use some mods for that? I've fixed these errors locally for now. But I'd like to reproduce that behaviour for some tests.
- There are some (30) blueprints which are written with an unsupported/to old version (0.18.10.1). My tool supports only 1.0 and newer.
- There are ~13 more blueprints with unknown errors. I'd like to analyse these.

I have tried to upload a ZIP with the blueprints the tool could parse in `--skip-bad` mode but Github does not allow uploading it here. The error is: `is not included in the list`. (Any ideas about that?) <strike>So you can download the file here:</strike>

--deleted--

The archive contains a blueprint import string and a file with the names of blueprints which cannot be parsed. The import file should help you to restore most blueprints in your downgraded game.

I will remove it as soon as you tell me you've got it.

**Comment by asheiduk** [comment]
@kevinmama Ping?

**Comment by asheiduk** [comment]
I've uploaded fixes for these issues:
- Any entity can request items after building (but only once). In this case: gun turrets and artillery turrets requested some ammo/shells. The vanillas game allows that only for modules.
- Any entity can have `tags`. Mods can save additional data there. In this case: `QuickbarTemplates`.
- Gun turrets and laser turrets can have a `direction` and `orientation`. Although these fields are forced to "North" when the blueprint is created. But mods can define custom turrets where these fields are preserved.
- Lamps have a strange copy of the `connect_to_logistic_network` flag. No other entity which can connect to the LN.

What is not fixed (and won't be):
- 30 blueprints which are stored in an old format (0.18.10.1). They can be skipped with the `--skip-bad`  mode.

Besides of the old blueprints the file can now be parsed :-)

**Comment by kevinmama** [comment]
Thanks for fixing the issue.

**Comment by kevinmama** [comment]
Thanks for fixing the issue.
